/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
  id("mim1qsdatagen.kotlin-application-conventions")
}

dependencies {
  implementation(project(":base"))
}

application {
  // Define the main class for the application.
  mainClass.set("mim1qsdatagen.cli.AppKt")
}
